### ISSUE TITLE
Wrap related code in container divs

### ISSUE THREAD

**Issue by griffinlacek** [eagobert/prj-rev-bwfs-dasmoto#2]
It's a good idea to wrap your related sections with a container div. I would add the h2, img, h3, and p since they are related. Moreover, if we do include them our indentation keeps them all at the same level (which needs to be indented one) because they are equal children elements of the div.

```
         <div>
           <h2></h2>
           <img></img>
           <h3></h3>
           <p></p>
         </div>
```
https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L15
https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L17-L20
https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L22-L25

**Comment by eagobert-zz** [comment]
Got it.  Thank you!
