### ISSUE TITLE
Repeated font-family styles

### ISSUE THREAD

**Issue by griffinlacek** [eagobert/prj-rev-bwfs-dasmoto#4]
Throughout your CSS you repeat font-family for Helvetica which could be set for the whole page by targeting body instead. It's always good to reduce repetitions so that your code is cleaner and more maintainable! 

https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L2
https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L11
https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L19
https://github.com/eagobert/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L35

**Comment by eagobert-zz** [comment]
I thought about that, but thought about this is an very straightforward way to show I could clearly follow the instructions.  This was great.  Thank you.
